controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    pause(500)
    projectile = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . f f . . . . . . . . 
        . . . . . f b b f . . . . . . . 
        . . . . f b b b b f . . . . . . 
        . . . . f b b b b f . . . . . . 
        . . . . . f b b f . . . . . . . 
        . . . . . . f f . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, mySprite, 200, 0)
    pause(1000)
})
let projectile: Sprite = null
let mySprite: Sprite = null
scene.setBackgroundColor(7)
scene.setBackgroundImage(img`
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeffffffffffffffff.........................................................................eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeefffeeeeeeeffffffffffffffff..................................................................bbbbbbbeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeefffeeeeeeebbbb.............................................................................bbbbbbbbeeeeefffeeeeeeeeeeeeeeeeeeeeeeeee
    eefffeeeeeeeeeeeeeeeeeeeeeeefffeeeeeeebbbb.............................................................................bbbbbbbbeeeeefffeeeeeeeeeeeeeeefffeeeeeee
    eefffeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbb............................................................................bbbbb....eeeeefffeeeeeeeeeeeeeeefffeeeeeee
    eefffeeeefffeeeeefffeeeeeeeeeeeeeeeeeebbbb............................................................................bbbb.....eeeeeeeeeeeeeeeeeeeeeeefffeeeeeee
    eeeeeeeeefffeeeeefffeeeeeeeeeeeeeeeeeebbbb............................................................................bbb......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeefffeeeeefffeeeeeeeeeeeeeeeeeebbbb............................................................................bbb......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbb.............................................................................bbbb....eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbb..............................................................................bbbbbbbeeeeeeeeeefffeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeefffeeeeeeeeeeebbbb..............................................................................bbbbbbbeeeeeeeeeefffeeeeeeeeeeeeeefffeee
    eeeeeeeeeeeeeeeeeeeeeeeefffeeeeeeeeeeebbbb..............................................................................bbbbbbbeeeeeeeeeeffffffeeeeeeeeeeefffeee
    eeeeeeeeeeeeeeeeeeeeeeeefffeeeeeeeeeeebbbb..............................................................................bbbb...eeeeeeeeeeeeefffeeeeeeeeeeefffeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbb..............................................................................bbb....eeeeeeeeeeeeefffeeeeeeeeeeeeeeeee
    eeeeeefffeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbb............................................................................bbbb.....eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeefffeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbbb...........................................................................bbbb.....eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeefffeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbbb...........................................................................bbb......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbbbb..........................................................................bbb......efffeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..bbbb..........................................................................bbbb.....efffeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeefffeeeeeeeeeeeeeeeeeeeeeee..bbbb..........................................................................bbbbb....efffeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeefffeeeeeeeeeeeeeeeeeeeeeee..bbbb..........................................................................bbbbbb...eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeefffeeeefffeeeeeeeeeeeeeeee..bbbb..........................................................................bbbbbbbb.eeeeeeeeeeeeeeeeeeeeeeeeeeeefffee
    eeeeeeeeeeeeeeeeeeefffeeeeeeeeeeeeeeee..bbbb..........................................................................bbbbbbbbbeeeeeeeeeeeeeeeeefffeeeeeeeefffee
    eeeeeeeeeeeeeeeeeeefffeeeeeeeeeeeeeeee.bbbbb..........................................................................bb.bbbbbbeeeeeeeeeeeeeeeeefffeeeeeeeefffee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.bbbbb..........................................................................bb..bbbbbeeeeeeeeeeeeeeeeefffeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.bbbbb........................................................................bbb........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbbbb......................................................................bbbb.........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbbbb......................................................................bbb..........eeeeeeeeeeeeeeeeeeeeeefffeeeeeeee
    eeeeeeeefffeeeeeeeeeeeeeeeeeeeeeeeeeeebbbbbb......................................................................bbb..........eeeeeeeeeeeeefffeeeeeefffeeeeeeee
    eeeeeeeefffeeeeeeeeeeeeeeeeeeeeeeeeeee..bbbb......................................................................bbb..........eeeeeeeeeeeeefffeeeeeefffeeeeeeee
    eeeeeeeefffeeeeeeeeeeeeeeeeeeeeeeeeeee...bbb......................................................................bbbbbbbbbbbbbeeeeeeeeeeeeefffeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeefffeeeeeeeeeee...bbb......................................................................bbbbbbbbbbbbbeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeefffeeeeeeeeeee...bbb......................................................................bbbbbbbbbbbbbeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeefffeeeeeeeeeee...bbb.....................................................................bbbbbbbbbbbbbbeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeefffeeeeeeeeeeeeeeeeeeee...bbb...................................................................bbbbbbb.........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeefffeeeeeeeeeeeeeeeeeeeebbbbbb...................................................................bbbbb...........eeeeeeeeeefffeeeeeeeeeeeeeeeeeeee
    eeeeefffeeeeeeefffeeeeeeeeeeeeeeeeeeeebbbbbbb..................................................................bbbb............eeeeeeeeeefffeeeeeeeeeeeeeeeeeeee
    eeeeefffeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbbbbbb..................................................................bbbb...........eeeeeeeeeefffeeeeeeeeeeeeeeefffee
    eeeeefffeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.bbbbbbbb....................................................................bbbbbbbb....eeeeeeefffeeeeeeeeeeeeeeeeeefffff
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee....bbbbb....................................................................bbbbbbbbbbbbeeeeeeefffeeeeeeeeeeeeeeeeeefffff
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.....bbbb....................................................................bbbbbbbbbbbbeeeeeeefffeeeeeeeeeeeeeeeeeeeeeff
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee......bbb......................................................................bbbbbbbbbbeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.....bbbb....................................................................bbbbbbbbbbbbeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...bbbbbb....................................................................bbbbbbbbb...eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeefffeeeeeeeeeeeeeeeee...bbbbbb..................................................................bbbbbbb.......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeefffeeeeeeeeeeeeeeeee...bbbbb................................................................bbbbbbb..........eeeeeeeeeeeeeeeeeeefffeeeeeeeeeee
    eeeeeeeeeeeeeeeeeefffeeeeeeeeeeeeeeeeebbbb...................................................................bbbbbb............eeeeeeeeeeeeeeeeeeefffeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbbbb.................................................................bbbbb.............eeeeeeeeeeeeeeeeeeffffeeeeeeeeeee
    eeeeeeefffeeeeeeeeeeeeeefffeeeeeeeeeeebbbbbbb................................................................bbbbbb............eeeeeeeeefffeeeeeefffeeeeeeeeeeee
    eeeeeeefffeeeeeeeeeeeeeefffeeeeeeeeeee.bbbbbbb................................................................bbbbbbb..........eeeeeeeeefffeeeeeefffeeeeeeeeeeee
    eeeeeeefffeeeeeeeeeeeeeefffeeeeeeeeeee...bbbbbbbb.............................................................bbbbbbbb.........eeeeeeeeefffeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee....bbbbbbbb..............................................................bbbbbbbb.bbbbbbeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee......bbbbbb................................................................bbbbbbbbbbbbbeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.........bbbb................................................................bbbbbbbbbbbbeeeeeeeeeeefffeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeefffee.........bbbb................................................................bbbbbbbbbbb.eeeeeeeeeeefffeeeeeeeeeeeeeefffee
    eeeeeeeeeeeeeeeeeefffeeeeeeeeeeeefffee..........bbb...............................................................bbbbbbbbbbb..eeeeeeeeeeefffeeeeeeeeeeeeeefffee
    eeeeeeeeeeeeeeeeeefffeeeeeeeeeeeefffee..........bbb..............................................................bbbbbbbbbb....eeeeeeeeeeeeeeeeeeeeeeeeeeeefffee
    eeeeeeeeeeeeeeeeeefffeeeeeeeeeeeeeeeee..........bbb.............................................................bbbbbb.........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeefffeeeeeeeeeeeeeeeeeeeeeeeeeee.........bbbb.............................................................bbbb...........eeeeefffeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeefffeeeeeeeeeeeeeeeeeeeeeeeeeee.........bbbb.............................................................bbbb...........eeeeefffeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeefffeeeeeeeeeeeeeeeeeeeeeeeeeee........bbbb..............................................................bbb............eeeeefffeeefffeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.......bbbbb..............................................................bbbb...........eeeeeeeeeeffffeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebb...bbbbbbbb..............................................................bbbb...........eeeeeeeeeeffffeeefffeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeefffeeeeeeebbbbbbbbbbbb................................................................bbb...........eeeeeeeeeefffeeeefffeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeefffeeeeeeebbbbbbbbbbb.................................................................bbbb..........eeeeeeeeefffeeeeefffeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeefffeeeeeeebbbbbbbb.....................................................................bbbbbbbbbbbb.eeeeeeeeefffeeeeeeeeeeeeeeeeeefff
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbbbbb........................................................................bbbbbbbbbbbeeeeeeeeefffeeeeeeeeeeeeeeeeeefff
    eeeeeeeeeeeeeeeeefffeeeeeeeeeeeeeeeeee..bbbbbb......................................................................bbbbbbbbbbbeeeeeeeeeeeeeeeeeeeeeeeeeeeeeefff
    eeeeeeeeeeeeeeeeefffeeeeeeeeeeeeeeeeee...bbbbb......................................................................bbbbbbbbbbbeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeefffeeeeeeeefffeeeeeeeeeeeeeeeeee....bbbbbbb...................................................................bbbb.......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeefffeeeeeeeeeeeeeeeeeeeeeeeeeeeee.....bbbbbbbb................................................................bbb.........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeefffeeeeeeeeeeeeeeeeeeeeeeeeeeeee......bbbbbbbb..............................................................bbbb.........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.........bbbbb..............................................................bbbb.........eeeeeeeeefffeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..........bbbb..............................................................bbbb.........eeeeeeeeefffeeeeeeeeeeeeeeefffeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeefffeeeee...........bbb..............................................................bbb..........eeeeeeeeefffeeeeeeeeeeeeeeefffeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeefffeeeee...........bbb..............................................................bbb..........eeeeeeeeeeeeeeeeeeeeeeeeeeefffeee
    eeeeeeeeeeeeeeeeeeefffeeeeeeeefffeeeee...........bbb..............................................................bbb..........eeeeeeeeeeeeeeeefffeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeefffeeeeeeeeeeeeeeee...........bbb................................................................b..........eeeeeeeeeeeeeeeefffeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeefffeeeeeeeeeeeeeeee...........bbb.................................................................bbbbbbbbbbeeeeeeeeeeeeeeeefffeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...........bbb.................................................................bbbbbbbbbbeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeefffeeeeeeeeeeeeeeeeeee...........bbb.................................................................bbbbbbbbbbeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeefffeeeeeeeefffeeeeeeeeeeeeeeeeeeebbbbb......bbb...................................................................bbbbbb..eeeeeeeeeeeefffeeeeeeeeeeeeeeeeee
    eeeeefffeeeeeeeefffeeeeeeeeeeeeeeeeeeebbbbbbbb..bbbb..................................................................bbb......eeeeeeeeeeeefffeeeeeeeeeeeeeeeeee
    eeeeefffeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbbbbbbbbbbbb.................................................................bb........eeeeeeeeeeeefffeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbbbbbbbbbbbb.................................................................bb........eeeeeeeeeeeeeeeeeeeeeeefffeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.bbbbbbbbbbbbb................................................................bbb........eeeeeeeeeeeeeeeeeeeeeeefffeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeefffeee..........bbbb................................................................bbb........eeeeeeeeeeeeeeeeeeeeeeefffeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeefffeee...........bbb................................................................bbb........eeeeeeeeeeeeeefffeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeefffeee...........bbb..............................................................bbbbbbb......eeeeeeeeeeeeeefffeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeefffeeeeeeeeeeee...........bbb...............................................................bbbbbbbbbbbbeeeeeffeeeeeeefffeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeefffeeeeeeeeeeee...........bbb...............................................................bbbbbbbbbbbbeeeeeffeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeefffeeeeeeeeeeee..........bbbb...............................................................bbbbbbbbbbbbeeeeeffeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeefffeeeeeeeeeeeeeeeeeeeeeeeeeeee..........bbbb...............................................................bbbbbbbbbbbbeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeefffeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbbb.....bbbb...............................................................bbbbb...bb..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeefffeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbbbbbbbbbbb................................................................bbbb........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbbbbbbbbbbb.................................................................bbb........eeeeeefffeeeeeeeeeeeeeefffeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbb...........................................................................bbb........eeeeeefffeeeeeeeeeeeeeefffeeeeeee
    eeeeeeeeeeeeeeeeeeeeefffeeeeeeeeeeeeeebbb...........................................................................bbb........eeeeeefffeeeeeeeeeeeeeefffeeeeeee
    eefffeeeeeeeeeeeeeeeefffeeeeeeeeeeeeeebbb...........................................................................bbb........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eefffeeeeeeeeeeeeeeeefffeeeeeeeeeeeeee.bbbbbbbbbbbbbbbb............................................................bbbbb.......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eefffeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...bbbbbbbbbbbbbbb.............................................................bbbb......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.....bbbbbb.bbbbbbb............................................................bbbbbb....eeeeeeeeeeefffeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee..............bbbbb............................................................bbbbbbbb..eeeeeeeeeeefffeeeeeeeeeeeeeeeeeee
    eeeeeeeeeefffeeeeeeeeeeeeeeeeeeeeeeeee................bbbb............................................................bbbbbbbbbeeeeeeeeeeeffffeeeeeeeeeeeeeeeeee
    eeeeeeeeeefffeeeeeeeeeeeeeefffeeeeeeeebbbbbb..........bbbb...............................................................bbbbbbeeeeeeeeeeeefffeeeeeeeeeefffeeeee
    eeeeeeeeeefffeeeeeeeeeeeeeefffeeeeeeeebbbbbbbbbb....bbbbbb............................................................bbbbbbbbbeeeeeffeeeeefffeeeeeeeeeefffeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeefffeeeeeeeebbbbbbbbbbbb.bbbbbbb..........................................................bbbbbbbbbbbeeeeeffeeeeeeeeeeeeeeeeeefffeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.bbbbbbbbbbbbbbbbbbb.......................................................bbbbbbbbbbbbb.eeeeeffeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.bbbbbbbbbbbbbbb...........................................................bbbbbbbb......eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee.........bbbbbb............................................................bbbbb.........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee...........bbbb............................................................bbb...........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee............bbbb...........................................................bbb...........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebb..........bbbb...........................................................bbbb..........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbbbbbbbbbb.bbb...........................................................bbbbb.........eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbbbbbbbbbbbbbb...........................................................bbbbb.........eeeeeeeeefffeeeeeeeeeeeeeeeeeeeee
    eefffeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbbbbbbbbbbbbbb............................................................bbbbb........eeeeeeeeefffeeeeeeeeeeeeeeeeefffe
    eefffeeeeeeeeeeeeeeeeeeeeefffeeeeeeeee..........bbbbbb.............................................................bbbbbb......efffeeeeefffeeeeeeeeeeeeeeeeefffe
    eefffeeeeeeeeeeeeeeeeeeeeefffeeeeeeeeeffff.fffff....................................................................bbbbbb.....efffeeeeeeeeeeeeeeeeeeeeeeeeefffe
    eeeeeeeeeeeeefffeeeeeeeeeefffeeeeeeeeeffffffffffffffff...............................................................bbbbbbbb..efffeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    eeeeeeeeeeeeefffeeeeeeeeeeeeeeeeeeeeeeffffffffffffffff................................................................bbbbbbb..eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
    `)
mySprite = sprites.create(img`
    .........................
    .........................
    ..........88888..........
    ..........888888.........
    ..........8888d..........
    ..........88bdd..........
    ..........ddbbb..........
    ......eeeeeebeeeeeeeb....
    ......eee86666f88fd......
    ........888888d88fd......
    .........88888d..........
    ........efeefff..........
    ........e8ee888..........
    .........888888..........
    .........8888f8..........
    .........f888f8..........
    .........ffffff..........
    .........ffffff..........
    ..........ff.ff..........
    ..........ff.ff..........
    ..........ff.ff..........
    ..........ff.ff..........
    ..........ffffff.........
    .........................
    .........................
    `, SpriteKind.Player)
let Enemies = sprites.create(img`
    .........................
    ..........22222..........
    .........ffffff..........
    ..........d2222..........
    ..........ddb22..........
    .....2....bbbdd..........
    ...ffff...22222..........
    .....fdf22fffff2.........
    .....fdf22d22222.........
    ..........d22222.........
    ..........fffeefe........
    ..........222ee2e........
    ..........222222.........
    ..........2f2222.........
    ..........2f222f.........
    ..........ffffff.........
    ..........ffffff.........
    ..........ff.ff..........
    ..........ff.ff..........
    ..........ff.ff..........
    ..........ff.ff..........
    .........ffffff..........
    .........................
    .........................
    .........................
    `, SpriteKind.Player)
animation.runImageAnimation(
mySprite,
[img`
    ........88888............
    ........888888...........
    ........8888d............
    ........88bdd............
    ........ddbbb............
    ....eeeeeebeeeeeeeb......
    ....eee86666f88fd........
    ......888888d88fd........
    .......88888d............
    ......efeefff............
    ......e8ee888............
    .......888888............
    .......8888f8............
    .......f888f8............
    .......f888f8............
    .......ffffff............
    .......ffffff............
    ........ff.ff............
    .......fff.fff...........
    .....ffff...fff..........
    .....fff.....ff..........
    .....f.......fff.........
    .........................
    .........................
    .........................
    `],
100,
true
)
Enemies.setPosition(146, 43)
controller.moveSprite(mySprite, 100, 100)
mySprite.setPosition(18, 36)
mySprite.setStayInScreen(true)
